Parameters:
  EC2InstanceBastionName:
    Type: String
    Default: bastion-0001-debian
  EC2SSHKeyBastionAccess:
    Type: AWS::EC2::KeyPair::KeyName
  VPCid:
    Type: AWS::EC2::VPC::Id
  VPCSubnetId:
    Type: List<AWS::EC2::Subnet::Id>
  EC2SecurityGroupidEC2Inst:
    Type: AWS::EC2::SecurityGroup::Id
  EC2SecurityGroupidVPCend:
    Type: AWS::EC2::SecurityGroup::Id
  EC2AMIid:
    Type: AWS::EC2::Image::Id

Resources:

## SETUP SSM ##

  SSMIAMRole0001:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: "/"

  SSMIAMInstanceProfile0001:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref SSMIAMRole0001

  SSMVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCid
      ServiceName: 


  
  EC2InstanceBastion:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EC2InstanceBastionName
      ImageId: !Ref EC2AMIid
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: t3.small
      IamInstanceProfile: !Ref SSMIAMInstanceProfile0001
      KeyName: !Ref EC2SSHKeyBastionAccess
      Monitoring: true
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash
          apt update
          apt full-upgrade -y
          apt install -y git curl wget openstack-clients vim awscli
          # Install SSM Agent
      SecurityGroupIds:
        - !Ref EC2SecurityGroupidEC2Inst
      SubnetId: !Ref VPCSubnetId
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs:
          DeleteOnTermination: false
          Encrypted: true
          VolumeSize: 20
          VolumeType: gp3
