Parameters:
  EC2InstanceBastionName:
    Type: String
    Default: bastion-0001-debian
  EC2SSHKeyBastionAccess:
    Type: String
    Default: sshkey-bastion-0001
  VPCid:
    Type: String
    Default: ""
  VPCPublicSubnetId:
    Type: String
    Default: ""
  EC2SecurityGroupid:
    Type: String
    Default: ""
  EC2AMIid:
    Type: String
    Default: ""
  PublicKeyMaterialAdmin:
    Type: String
    Default: ""

Resources:
  SSHKeyBastionAccess:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref EC2SSHKeyBastionAccess
      PublicKeyMaterial: !Ref PublicKeyMaterialAdmin

## SETUP SSM ##

  EC2InstanceBastion:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EC2InstanceBastionName
      ImageId: !Ref EC2AMIid
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: t3.small
      KeyName: !Ref EC2SSHKeyBastionAccess
      Monitoring: true
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash
          apt update
          apt full-upgrade -y
          apt install -y git curl wget openstack-clients vim awscli
          # Install SSM Agent
      SecurityGroupIds:
        - !Ref EC2SecurityGroupid
      SubnetId: !Ref VPCPublicSubnetId
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs:
          DeleteOnTermination: false
          Encrypted: true
          VolumeSize: 20
          VolumeType: gp3
